### ISSUE TITLE
input type="number" for android

### ISSUE THREAD

**Issue by bux578** [KoffeinFlummi/Arma3Spotter#15]
Can't enter negative numbers on Galaxy S5 (chrome).

![image](https://cloud.githubusercontent.com/assets/1235520/5564014/975fff46-8ea3-11e4-8df7-9d501b8cf9ad.png)

vs.

![image](https://cloud.githubusercontent.com/assets/1235520/5564011/8fb377e6-8ea3-11e4-9368-beaee1de6c64.png)

**Comment by DarkWanderer** [comment]
I don't have such issue - nexus 5, android 5 (screenshot)

![arma3spotter](https://cloud.githubusercontent.com/assets/2542609/6144024/9e94a8ea-b1e2-11e4-8817-cb7e43fdd557.png)
