### ISSUE TITLE
Massi's SR25

### ISSUE THREAD

**Issue by AlphaKilo07** [KoffeinFlummi/Arma3Spotter#26]
AGM BALLISTIC DATA EXPORT

Add everything below the line to /src/data/weapons.json:

====================

  {
    "type": "srifle_mas_sr25",
    "name": "SR25",
    "mod": "[mod containing weapon]",
    "magazines": [
      {
        "type": "20Rnd_mas_762x51_Stanag",
        "ammo": "B_mas_762x51_Ball",
        "name": "20rnd 7.62mm Mag",
        "initSpeed": 911,
        "airFriction": -0.0009324,
        "timeToLive": 6,
        "simulationStep": 0.05
      },
      {
        "type": "20Rnd_mas_762x51_T_Stanag",
        "ammo": "B_mas_762x51_Ball_T",
        "name": "20rnd 7.62mm Mag(Tracer)",
        "initSpeed": 911,
        "airFriction": -0.0009324,
        "timeToLive": 6,
        "simulationStep": 0.05
      },
      {
        "type": "20Rnd_762x51_Mag",
        "ammo": "AGM_B_762x51_M118LR",
        "name": "7.62mm 20Rnd Mag",
        "initSpeed": 792,
        "airFriction": -0.0008577,
        "timeToLive": 6,
        "simulationStep": 0.05
      }
    ]
  }

====================

Do not forget to add a comma behind the previous last entry after you insert this weapon and please name the mod adding the current weapon. Also, if you ran this script in a non-English version of the game, please correct the names for rifle and magazines to use the English version.

**Comment by KoffeinFlummi** [comment]
Added in #28
