### ISSUE TITLE
Export Script Does Not Track Mod

### ISSUE THREAD

**Issue by AlphaKilo07** [KoffeinFlummi/Arma3Spotter#27]
Currently the export script will leave out the mod because it uses "[mod containing weapon]" instead of the mod. Example:

AGM BALLISTIC DATA EXPORT

Add everything below the line to /src/data/weapons.json:

====================

  {
    "type": "srifle_mas_sr25",
    "name": "SR25",
   ** "mod": "[mod containing weapon]",**
    "magazines": [
      {
        "type": "20Rnd_mas_762x51_Stanag",
        "ammo": "B_mas_762x51_Ball",
        "name": "20rnd 7.62mm Mag",
        "initSpeed": 911,
        "airFriction": -0.0009324,
        "timeToLive": 6,
        "simulationStep": 0.05
      },
      {
        "type": "20Rnd_mas_762x51_T_Stanag",
        "ammo": "B_mas_762x51_Ball_T",
        "name": "20rnd 7.62mm Mag(Tracer)",
        "initSpeed": 911,
        "airFriction": -0.0009324,
        "timeToLive": 6,
        "simulationStep": 0.05
      },
      {
        "type": "20Rnd_762x51_Mag",
        "ammo": "AGM_B_762x51_M118LR",
        "name": "7.62mm 20Rnd Mag",
        "initSpeed": 792,
        "airFriction": -0.0008577,
        "timeToLive": 6,
        "simulationStep": 0.05
      }
    ]
  }

====================

**Comment by KoffeinFlummi** [comment]
This is unfortunately not possible as there is no way to (reliably) find out what mod introduced a weapon. The only things you could (!) get, is the author's name or the CfgPatches class name, but neither of them would be the actual name of the mod.
