### ISSUE TITLE
[Feature suggestion]Range Table mode

### ISSUE THREAD

**Issue by DarkWanderer** [KoffeinFlummi/Arma3Spotter#29]
It would be useful to have a precalculated range table mode, so that the values can be input just from a quick glance at the table. This will supplement the current "precision mode", allowing for quicker acquisition for close-range targets or pre-cooking of the adjustment based on range, while spotter calculates exact values
The data style can be similar to ACE's:
![ACE range table](http://i.ytimg.com/vi/MlKtKqpCaWw/maxresdefault.jpg)

**Comment by DaTomyz** [comment]
Well... you can make your own range tables with the calculator, just get a paper, write some numbers and you're done in 15 minutes... It's not THAT necessary that koffein gives all chewed to us

**Comment by DarkWanderer** [comment]
I suppose KoffeinFlummi is grown up enough to deal with feature requests
himself?
