### ISSUE TITLE
Add all bullets Trixie's Sniper/Marksman pack

### ISSUE THREAD

**Issue by DaTomyz** [KoffeinFlummi/Arma3Spotter#36]
AGM BALLISTIC DATA EXPORT

Add everything below the line to /src/data/weapons.json:

====================

  {
    "type": "Trixie_M107_Black",
    "name": "Barret M107 (Black)",
    "mod": "[mod containing weapon]",
    "magazines": [
      {
        "type": "Trixie_10x127_mag",
        "ammo": "B_127x108_Ball",
        "name": "10Rnd 12.7x99mm",
        "initSpeed": 820,
        "airFriction": -0.00086,
        "timeToLive": 10,
        "simulationStep": 0.05
      },
      {
        "type": "Trixie_10x127_HE_Mag",
        "ammo": "Trixie_127_HE_Ball",
        "name": "10Rnd 12.7x99mm HE",
        "initSpeed": 1060,
        "airFriction": -0.00086,
        "timeToLive": 10,
        "simulationStep": 0.05
      },
      {
        "type": "Trixie_10x127_HEIAP_Mag",
        "ammo": "B_127x108_APDS",
        "name": "10Rnd Raufoss Mk 211 HEIAP",
        "initSpeed": 1060,
        "airFriction": -0.00036,
        "timeToLive": 10,
        "simulationStep": 0.05
      }
    ]
  }

====================

Do not forget to add a comma behind the previous last entry after you insert this weapon and please name the mod adding the current weapon. Also, if you ran this script in a non-English version of the game, please correct the names for rifle and magazines to use the English version.

**Comment by KoffeinFlummi** [comment]
Added in d4759d8.

Please consider creating a pull request in the future though.
